def format_report(analysis, risk):
    """
    Format and safely split the AI hedge fund report into Telegram-friendly chunks.
    Telegram bots have a 4096-character message limit, so we’ll handle that gracefully.
    """
    if "error" in analysis or "error" in risk:
        return ["⚠️ Analysis failed due to missing or invalid data."]

    full_report = f"""
📊 **AI Hedge Fund Research Report**
------------------------------------

**Symbol:** {analysis.get('symbol', 'N/A')}

**Market & News Analysis:**
{analysis.get('analysis', 'No analysis available')}

**Risk Management Summary:**
{risk.get('risk_report', 'No risk report available')}

------------------------------------
💼 *Generated by your AI Hedge Fund Research Agent*
"""

    # Telegram message limit is 4096 chars — split into clean chunks at paragraph breaks
    chunks = []
    while len(full_report) > 4000:
        split_index = full_report.rfind("\n", 0, 4000)
        if split_index == -1:
            split_index = 4000
        chunks.append(full_report[:split_index].strip())
        full_report = full_report[split_index:]
    chunks.append(full_report.strip())

    return chunks
